import type * as estree from 'estree';
import { type StripMeta } from './javaScriptParser.js';

export type JavaScriptProgram = StripMeta<estree.Program>;
export type JavaScriptStatement = StripMeta<estree.Statement>;
export type JavaScriptExpression = StripMeta<estree.Expression>;
export type JavaScriptIdentifier = StripMeta<estree.Identifier>;
export type JavaScriptLiteral = StripMeta<estree.Literal>;
export type JavaScriptBlockStatement = StripMeta<estree.BlockStatement>;
export type JavaScriptExpressionStatement = StripMeta<estree.ExpressionStatement>;
export type JavaScriptVariableDeclaration = StripMeta<estree.VariableDeclaration>;
export type JavaScriptVariableDeclarator = StripMeta<estree.VariableDeclarator>;
export type JavaScriptIfStatement = StripMeta<estree.IfStatement>;
export type JavaScriptWhileStatement = StripMeta<estree.WhileStatement>;
export type JavaScriptForStatement = StripMeta<estree.ForStatement>;
export type JavaScriptReturnStatement = StripMeta<estree.ReturnStatement>;
export type JavaScriptThrowStatement = StripMeta<estree.ThrowStatement>;
export type JavaScriptTryStatement = StripMeta<estree.TryStatement>;
export type JavaScriptCatchClause = StripMeta<estree.CatchClause>;
export type JavaScriptEmptyStatement = StripMeta<estree.EmptyStatement>;
export type JavaScriptFunctionDeclaration = StripMeta<estree.FunctionDeclaration>;
export type JavaScriptFunctionExpression = StripMeta<estree.FunctionExpression>;
export type JavaScriptArrowFunctionExpression = StripMeta<estree.ArrowFunctionExpression>;
export type JavaScriptBinaryExpression = StripMeta<estree.BinaryExpression>;
export type JavaScriptLogicalExpression = StripMeta<estree.LogicalExpression>;
export type JavaScriptUnaryExpression = StripMeta<estree.UnaryExpression>;
export type JavaScriptUpdateExpression = StripMeta<estree.UpdateExpression>;
export type JavaScriptAssignmentExpression = StripMeta<estree.AssignmentExpression>;
export type JavaScriptConditionalExpression = StripMeta<estree.ConditionalExpression>;
export type JavaScriptCallExpression = StripMeta<estree.SimpleCallExpression>;
export type JavaScriptNewExpression = StripMeta<estree.NewExpression>;
export type JavaScriptMemberExpression = StripMeta<estree.MemberExpression>;
export type JavaScriptArrayExpression = StripMeta<estree.ArrayExpression>;
export type JavaScriptObjectExpression = StripMeta<estree.ObjectExpression>;
export type JavaScriptProperty = StripMeta<estree.Property>;
export type JavaScriptThisExpression = StripMeta<estree.ThisExpression>;
